version: "3.9"
services:
  
  paper-server:
    build: 
     context: .
     dockerfile: Dockerfile

    volumes:
      - ../:/home/work

    environment:
      HOME: "/home/work/"



    env_file: 
      - "../env/env.env"
      - "../env/azurite.env"
      - "../env/credential.env"
    # ports:
    #   - 5000:5000


    restart: always
    working_dir: /home/work
    container_name: paper-server


    command: sleep 400000

  paper-db:
    image: mysql:8.0.1
    container_name: paper-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paper-db
      MYSQL_USER: hashimoto
      MYSQL_PASSWORD: hashimoto
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ../mysql_server/db/data:/var/lib/mysql
    - ../mysql_server/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ../mysql_server/db/sql:/docker-entrypoint-initdb.d
  
  paper-client:
    build: 
     context: .
     dockerfile: Dockerfile_react
    container_name: paper-client
    volumes:
      - ../paper-client:/usr/src/app
    command: sh -c "cd react-app && yarn start"
    env_file: 
      - "../env/API.env"
    
    # ports:
    #   - "3000:3000"

  paper-azurite:
    build: 
     context: .
     dockerfile: Dockerfile_azurite
    container_name: paper-azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - ../azurite:/data
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 -l /data"

      #  paper-azurite-cli:
      #image: mcr.microsoft.com/azure-storage/azurite-cli     
      #container_name: paper-azurite-cli    
      #    command: sleep 1000000000    




